version: '3.8'

services:
#  app:
#    image: your-app-image # Replace with your application image
#   volumes:
#      - .:/workspace
#    depends_on:
#      - sqlserver1
#      - sqlserver2

  sqlserver1:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver1-data:/var/opt/mssql

  sqlserver2:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1434"
    volumes:
      - sqlserver2-data:/var/opt/mssql

volumes:
  sqlserver1-data:
  sqlserver2-data: